const path=require('path'); require('dotenv').config({path:path.join(__dirname,'../server/.env')});
const { PrismaClient } = require(path.join(__dirname,'../server/node_modules/@prisma/client')); const bcrypt=require(path.join(__dirname,'../server/node_modules/bcryptjs'));
const prisma=new PrismaClient();
async function main(){
 const admin=await prisma.user.upsert({where:{email:'admin@passportdemo.com'},update:{},create:{name:'System Administrator',email:'admin@passportdemo.com',password:await bcrypt.hash('Admin@123',10),role:'ADMIN',phone:'9000000001',city:'Chennai',state:'Tamil Nadu',pincode:'600001'}});
 const names=[['Ananya Sharma','applicant@passportdemo.com','9000000002'],['Rahul Kumar','rahul@passportdemo.com','9000000003'],['Meera Iyer','meera@passportdemo.com','9000000004']];
 const users=[]; for(const [name,email,phone] of names) users.push(await prisma.user.upsert({where:{email},update:{},create:{name,email,phone,password:await bcrypt.hash('Applicant@123',10),role:'APPLICANT',city:'Chennai',state:'Tamil Nadu',pincode:'6000'+(10+users.length)}}));
 const statuses=['SUBMITTED','DOCUMENT_VERIFICATION','POLICE_VERIFICATION','APPROVED','DISPATCHED'];
 for(let i=0;i<5;i++){const u=users[i%3]; const n=`PAS-2026-${String(i+1).padStart(5,'0')}`; const app=await prisma.passportApplication.upsert({where:{applicationNumber:n},update:{},create:{applicationNumber:n,userId:u.id,status:statuses[i],passportType:i%2?'Ordinary':'Ordinary',applicationType:i%2?'Reissue':'Fresh Passport',placeOfBirth:'Chennai, Tamil Nadu',maritalStatus:'Single',employmentType:'Student',submittedAt:new Date(Date.now()-i*86400000)}}); await prisma.document.createMany({data:[{applicationId:app.id,documentType:'Identity Proof',fileName:'Aadhaar_Demo.pdf',fileUrl:'#',verificationStatus:i>0?'VERIFIED':'PENDING'},{applicationId:app.id,documentType:'Address Proof',fileName:'Address_Demo.pdf',fileUrl:'#',verificationStatus:i>1?'VERIFIED':'PENDING'}],skipDuplicates:true}); if(i>=2) await prisma.policeVerification.upsert({where:{applicationId:app.id},update:{status:i===2?'IN_PROGRESS':'VERIFIED',officerName:'Officer Demo'},create:{applicationId:app.id,status:i===2?'IN_PROGRESS':'VERIFIED',officerName:'Officer Demo',verificationDate:new Date()}}); await prisma.notification.create({data:{userId:u.id,title:'Application Update',message:`Your application ${n} is currently ${statuses[i].replaceAll('_',' ')}.`}}); }
 await prisma.auditLog.create({data:{userId:admin.id,action:'SEED_DATA',description:'Demo environment initialized.'}});
 console.log('Seed complete'); }
main().catch(e=>{console.error(e);process.exit(1)}).finally(()=>prisma.$disconnect());
